---
directory: C:\ProgramData\chocolatey\lib\simplewall.portable\tools\simplewall\64\
file_rules: profile.xml
janelas_simplewall_path_rules: '{{ directory }}{{ file_rules }}'
program: simplewall
version: 3.1.2
