---
- hosts: group_win_ueds
  connection: winrm
  gather_facts: no
  tasks:
    - name: "Visual Studio for UE"
      import_tasks: atasks-win-msvs-for-ue.yml
    ##- name: Epic Games Launcher
      # https://chocolatey.org/packages/epicgameslauncher
      ##win_chocolatey:
        ##name: epicgameslauncher
    - name: "SSH client [chocolatey] (because we need SCP)"
      include_tasks: atasks-win-ssh-client.yml
    - name: "SCP facts"
      include_tasks: atasks-scp-facts.yml
    - name: "Unreal Engine 4.24"
      vars:
          dirparent: "Epic Games"
          directory: "UE_4.24"
          ## NO LONGER USING WIN LOCAL DIREcTORY BEcAUSE ITS WAY TOO SLOW
          #source: "/mnt/opt/{{ dirparent }}/{{ directory }}"
          zipfile: "{{ directory }}.zip"
          srczipfile: "{{ scppath }}{{ directory }}.zip"
          destparent: "C:/opt/{{ dirparent }}/"
          destzipfile: "{{ destparent }}{{ zipfile }}"
          target: "{{ destparent }}{{ directory }}"
      include_tasks: atasks-win-establish-directory.yml
      ## this will force over existing directory:
      ##include_tasks: atasks-win-zip-and-copy-directory.yml
...
