---
- hosts: group_win_ueds
  connection: winrm
  gather_facts: no
  tasks:
    - name: "Visual Studio for UE"
      import_tasks: atasks-win-msvs-for-ue.yml
    ##- name: Epic Games Launcher
      # https://chocolatey.org/packages/epicgameslauncher
      ##win_chocolatey:
        ##name: epicgameslauncher
    - name: "Copy UE to remote"
      vars:
          parentdir: "Epic Games"
          directory: "UE_4.24"
          source: "/mnt/opt/{{ parentdir }}/{{ directory }}"
          zipfile: "{{ directory }}.zip"
          destparent: "C:\\opt\\{{ parentdir }}\\"
          destzipfile: "{{ destparent }}{{ zipfile }}"
          target: "{{ destparent }}{{ directory }}"
      include_tasks: atasks-win-establish-directory.yml
      ## this will force over existing directory:
      ##include_tasks: atasks-win-zip-and-copy-directory.yml
...
