---
- hosts: group_win_ueds
  connection: winrm
  gather_facts: no
  vars:
    uever: 4.24
  tasks:
    - include_tasks: atasks-win-firewall-config-isolated.yml
    - include_tasks: atasks-win-update-disable.yml
    - include_tasks: atasks-win-remote-desktop.yml
    - include_tasks: atasks-win-janelas-user.yml

    ## TODO: !!! BEGIN REQUIRED INTERNET ACCESS FOR Chocolately
    - include_tasks: atasks-win-firewall-off.yml
    - name: "Visual C++ Redistributables required by UE"
      include_tasks: atasks-win-vcredist-for-ue.yml
    ## TODO: !!! END REQUIRED INTERNET ACCESS FOR Chocolately
    - include_tasks: atasks-win-firewall-on.yml

    ## TODO: Visual Studio is not yet required to package BP-only projects
    ##- name: "Visual Studio for UE"
    ##  include_tasks: atasks-win-vs-for-ue.yml

    ## TODO: we don't want the Launcher yet
    ##- name: Epic Games Launcher
    ##   https://chocolatey.org/packages/epicgameslauncher
    ##  win_chocolatey:
    ##    name: epicgameslauncher

    ## SSH and SCP already present on cloud Win Server 2019
    ##- name: "SSH client [chocolatey] (because we need SCP)"
    ##  include_tasks: atasks-win-ssh-client.yml

    # TODO: fails on Win 10 Pro, and cloud Win Server 2019 doesn't need it
    ##- name: "DirectX 9 (required by UE 4.24)"
    ##  win_chocolatey:
    ##    name: directx
    ##  #ignore_errors: yes # TODO: ### says it fails on Win 10 Pro even though log says it succeeded

    - name: "SCP facts"
      include_tasks: atasks-scp-facts.yml

    ## TODO: DOES NOT ELIMINATE ERROR WITH XAudio2_7.dll
    ##- name: "DirectX 9 from MS redist (because chocolatey fails)"
    ##  vars:
    ##    dirparent: ms
    ##    stem: directx_Jun2010_redist
    ##    file: "{{ stem }}.exe"
    ##    srcfile: "{{ scppath }}{{ file }}"
    ##    destparent: "C:/soft/gratis/{{ dirparent }}/"
    ##    target: "{{ destparent }}{{ file }}"
    ##    replacetarget: no
    ##  block:
    ##    - name: "copy DirectX 9 installer from SCP"
    ##      include_tasks: atasks-win-establish-file.yml
    ##    ## TODO: directx_Jun2010_redist is ONLY extraction, not intaller
    ##    ## TODO: DIRECTX.exe /silent is the actuall installer
    ##    ## TODO: BUT it fails even with manual install
    ##    ##- name: "establish DirectX 9"
    ##    ##  win_package:
    ##    ##    #product_id: '{F9EC45F9-074A-48BF-92E9-A8CADD56F693}'
    ##    ##    product_id: 'ANSIBLE PLACEHOLDER FOR DIRECTX 9'
    ##    ##    # found using rededt32.exe at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{F9EC45F9-074A-48BF-92E9-A8CADD56F693}
    ##    ##    # DisplayName: UE4 Prerequisites (x64)
    ##    ##    # DisplayVersion: 1.0.11.0
    ##    ##    path: "{{ target }}"
    ##    ##    arguments: "/Q /T:{{ destparent }}{{ stem }}"

    - name: "Unreal Engine {{ uever }}"
      vars:
        dirparent: "Epic_Games" # !!! replaced space with _ in 'Epic Games'
        directory: "UE_{{ uever }}"
        zipfile: "{{ directory }}.zip"
        srczipfile: "{{ scppath }}{{ zipfile }}"
        destparent: "C:/opt/{{ dirparent }}/"
        destzipfile: "{{ destparent }}{{ zipfile }}"
        target: "{{ destparent }}{{ directory }}"
        targetbin: "{{ target }}/Engine/Binaries"
        targetbintp: "{{ targetbin }}/ThirdParty"
        targetbin64: "{{ targetbin }}/Win64"
        targetexe64: "{{ targetbin64 }}/UE4Editor.exe"
        replacetarget: no
        replacezipfile: no
      block:
        - include_tasks: atasks-win-establish-directory.yml

        ## TODO: ### FAILS WITH RC 1603, PROBABLY NEEDS NET FRAMEWORK 4
        ## TODO: doesn't fully install from ansible because GUI asks to download .NET fraamework
        ##- name: Unreal Engine {{ uever }} Prerequisites installation
        ##  #win_command: "{{ target }}/Engine/Extras/Redist/en-us/UE4PrereqSetup_x64.exe"
        ##  win_package:
        ##    product_id: '{F9EC45F9-074A-48BF-92E9-A8CADD56F693}'
        ##      # found using rededt32.exe at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{F9EC45F9-074A-48BF-92E9-A8CADD56F693}
        ##      # DisplayName: UE4 Prerequisites (x64)
        ##      # DisplayVersion: 1.0.11.0
        ##    path: "{{ target }}/Engine/Extras/Redist/en-us/UE4PrereqSetup_x64.exe"
        ##    arguments: /quiet

        ## TODO: DOES NOT ELIMINATE ERROR WITH XAudio2_7.dll
        ## TODO: @@@ PREPARE ZIP WITH THIS IN ADVANCE
        ##- name: Unreal Editor {{ uever }} copy required old DLLs to UE4 bin, set 1
        ##  win_copy:
        ##    remote_src: yes
        ##    src: "{{ targetbintp }}/AppLocalDependencies/Win64/DirectX/"
        ##    dest: "{{ targetbin64 }}"

        ## TODO: ### UE4 Editor CRASHES WITH THIS:
        ##- name: "copy required old DLLs to UE4 bin, set 2"
        ##  win_copy:
        ##    remote_src: yes
        ##    src: "{{ targetbintp }}/CEF3/Win64/"
        ##    dest: "{{ targetbin64 }}"

        - name: Unreal Editor {{ uever }} shortcut
          win_shortcut:
            description: configured by Luar devops
            directory: "{{ targetbin64 }}"
            src: "{{ targetexe64 }}"
            icon: "{{ targetexe64 }},0"
            dest: "C:/Users/Public/Desktop/Unreal Editor {{ uever }}.lnk"
...
