---
- name: "checking existence of remote {{ target }}"
  win_stat: path={{ target }} get_checksum=False get_md5=False
  register: win_stat_target

- name: "zip and copy {{ source }} to {{ target }}"
  include_tasks: atasks-win-zip-and-copy-directory.yml
  when: win_stat_target.stat.exists == False
...
