---
- name: "checking existence of local zip {{ zipfile }}"
  stat: path={{ zipfile }} get_checksum=False get_md5=False
  delegate_to: localhost
  run_once: true
  register: stat_zipfile

- name: "locally zip {{ source }}"
  archive: path={{ source }} dest={{ zipfile }} format=zip creates={{ zipfile }}
  delegate_to: localhost
  run_once: true
  when: stat_zipfile.stat.exists == False

- name: "send {{ zipfile }} to remote {{ destparent }}"
  win_copy: src={{ zipfile }} dest={{ destparent }}

- name: "remote unzip into {{ target }}"
  win_unzip: src={{ destzipfile }} dest={{ destparent }}

##@ @@@ LEAVE ZIP ON REMOTE FOR NOW
##- name: "remote delete {{ destzipfile }}"
##  win_file: path={{ destzipfile }} state=absent
...
