---
- name: "establish remote parent directory {{ destparent }}"
  win_file: path={{ destparent }} state=directory

- name: "check existence of remote {{ target }}"
  win_stat: path={{ target }} get_checksum=False get_md5=False
  register: win_stat_target

- name: "check existence of remote {{ destzipfile }}"
  win_stat: path={{ destzipfile }} get_checksum=False get_md5=False
  register: win_stat_zipfile

- name: "SCP from {{ srczipfile }} to {{ destparent }}"
  vars:
    scpsrc: "{{ srczipfile }}"
    scpdest: "{{ destparent }}"
  include_tasks: atasks-win-scp-remote.yml
  when: win_stat_target.stat.exists == False and win_stat_zipfile.stat.exists == False

- name: "remote unzip into {{ target }}"
  win_unzip: src={{ destzipfile }} dest={{ destparent }}
  when: win_stat_target.stat.exists == False
...
