---
- set_fact:
    janelas_user_groups:
      - Users

- set_fact:
    janelas_user_groups: "{{ janelas_user_groups + [item] }}"
  with_items:
    - Remote Desktop Users
  when: janelas_user_remotable is defined and janelas_user_remotable == True

- name: user "{{ janelas_user_name }}"
  win_user:
    name: "{{ janelas_user_name }}"
    groups: "{{ janelas_user_groups }}"
    #password: "{{ janelas_user_password | password_hash('sha512') }}"
    password: "{{ janelas_user_password }}"
    password_expired: yes
    password_never_expires: yes
    update_password: on_create

- name: user profile "{{ janelas_user_name }}"
  win_user_profile:
    username: "{{ janelas_user_name }}"

### TODO: DOES NOTHING
###- name: user right for Remote Desktop"
###  win_user_right:
###    name: SeRemoteInteractiveLogonRight
###    users:
###    - "{{ janelas_user_name }}"
###  when: janelas_user_remotable is defined and janelas_user_remotable == True
