#!/bin/bash
PATH_TO_THIS=`dirname $0`
source $PATH_TO_THIS/env-ansible
if [ $# -lt 1 ]
then
    echo ""
    echo usage: "$0 <playbook name between apb-???.yml>"
    echo ".....available playbook names:"
    for FILE in `ls apb-*.yml`
    do
      [[ $FILE =~ apb-(.*).yml$ ]]
      echo ${BASH_REMATCH[1]}
    done
    exit 1
fi
ansible-playbook -i $FILE_INVENTORY $ARG_EXTRA_VARS -vv apb-$1.yml $2 $3 $4 $5 $6 $7 $8 $9
