---
- name: "firewall rule to block OUT all UDP"
  win_firewall_rule:
    name: BLOCK OUT ALL UDP
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: out
    protocol: UDP
    remoteport: any
...
