---
- name: DISABLE service Update Orchestrator Service
  win_service:
    name: UsoSvc
    start_mode: disabled # win default Automatic (Delayed Start)
    state: stopped
    force_dependent_services: yes

- name: DISABLE service Windows Update
  win_service:
    name: wuauserv
    start_mode: disabled # win default Automatic
    state: stopped
    force_dependent_services: yes
...
