---
- name: "firewall rule IN to block all UDP"
  win_firewall_rule:
    name: BLOCK IN ALL UDP
    group: naluar
    state: present
    enabled: yes
    action: block
    direction: in
    protocol: UDP
    localport: any
...
