---
- name: "ENABLE Remote Desktop by registry edit"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword

### TODO: NOT REQUIRED FOR Windows Server 2019
##- name: "ENABLE Remote Desktop, registry edit 2 of 2"
##  win_regedit:
##    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
##    name: TSUserEnabled
##    data: 1
##    type: dword

### TODO: ALREADY DEFAULTS TO 0 ON Windows Server 2019
##- name: "ENABLE Remote Desktop, registry edit 3 of 3"
##  win_regedit:
##    path: HKLM:\SOFTWARE\Microsoft\Windows\NT\CurrentVersionl\Windlogon
##    name: WinStationsDisabled
##    data: 0
##    type: string

- name: "assign port of Remote Desktop by registry edit"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: PortNumber
    data: "{{ janelas_port_winrdp }}"
    type: dword
  when: janelas_port_winrdp is defined
  register: winrdpport

- name: "restart Remote Desktop service"
  win_service:
    name: Remote Desktop Services
    state: restarted
    force_dependent_services: yes
  when: winrdpport.changed

- name: "CREATE rule for different port of Remote Desktop firewall rule predefined in Windows"
  win_firewall_rule:
    name: janelas RDP TCP IN
    group: __janelas__
    state: present
    enabled: yes
    action: allow
    direction: in
    protocol: TCP
    localport: "{{ janelas_port_winrdp }}"
    program: "C:\\Windows\\system32\\svchost.exe"
    service: termservice
  when: janelas_port_winrdp is defined

- name: "DISABLE/ENABLE Remote Desktop firewall rule predefined by Windows"
  win_firewall_rule:
    name: Remote Desktop - User Mode (TCP-In)
    group: Remote Desktop
    enabled: "{{ janelas_port_winrdp is not defined }}"

### TODO: UDP IS NOT REQUIRED BUT MAY IMPROVE PERFORMANCE (UNTESTED)
##- name: "ENABLE firewall rule predefined in Windows, 2 of 3"
##  win_firewall_rule:
##    name: Remote Desktop - User Mode (UDP-In)
##    group: Remote Desktop
##    enabled: yes

### TODO: DOES NOT SEEM TO BE REQUIRED ON Windows Server 2019
##- name: "ENABLE firewall rule predefined in Windows, 3 of 3"
##  win_firewall_rule:
##    name: Remote Desktop - Shadow (TCP-In)
##    group: Remote Desktop
##    enabled: yes
...
