---
- name: "firewall rule to block OUT all UDP"
  win_firewall_rule:
    name: BLOCK OUT ALL UDP
    group: naluar
    state: present
    enabled: yes
    action: block
    direction: out
    protocol: UDP
    remoteport: any
...
