---
- name: "firewall rule IN for only PS, Win RD, and RM, lowest TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BELOW WinRD 33
    group: __janelas__
    state: present
    enabled: yes
    action: block
    direction: in
    protocol: TCP
    localport: 0-32

- name: "firewall rule IN for only PS, Win RD and RM, lower TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BETWEEN WinRD 33 AND PS 5900
    group: __janelas__
    state: present
    enabled: yes
    action: block
    direction: in
    protocol: TCP
    localport: 34-5899

- name: "firewall rule IN for only PS, Win RD and RM, middle TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BETWEEN PS 5900 AND WinRM 5986
    group: __janelas__
    state: present
    enabled: yes
    action: block
    direction: in
    protocol: TCP
    localport: 5901-5985

- name: "firewall rule IN for only PS, Win RD and RM, upper TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BETWEEN WinRM 5986 AND PS 9980
    group: __janelas__
    state: present
    enabled: yes
    action: block
    direction: in
    protocol: TCP
    localport: 5987-9979

- name: "firewall rule IN for only PS, Win RD and RM, upmost TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BEYOND PS 9982
    group: __janelas__
    state: present
    enabled: yes
    action: block
    direction: in
    protocol: TCP
    localport: 9983-65535
...
