---
- name: "Unreal Engine {{ uever }}"
  vars:
    dirparent: "Epic_Games" # !!! replaced space with _ in 'Epic Games'
    directory: "UE_{{ uever }}"
    zipfile: "{{ directory }}.zip"
    srczipfile: "{{ scppath }}{{ zipfile }}"
    destparent: "C:/opt/{{ dirparent }}/"
    destzipfile: "{{ destparent }}{{ zipfile }}"
    target: "{{ destparent }}{{ directory }}"
    targetbin: "{{ target }}/Engine/Binaries"
    targetbintp: "{{ targetbin }}/ThirdParty"
    targetbin64: "{{ targetbin }}/Win64"
    targetexe64: "{{ targetbin64 }}/UE4Editor.exe"
    replacetarget: no
    replacezipfile: no
  block:
    - include_role:
        name: filecopy
        tasks_from: atasks-win-establish-directory.yml

    ## TODO: ### FAILS WITH RC 1603, PROBABLY NEEDS NET FRAMEWORK 4
    - name: Unreal Engine {{ uever }} Prerequisites installation
      #win_command: "{{ target }}/Engine/Extras/Redist/en-us/UE4PrereqSetup_x64.exe"
      win_package:
        product_id: '{F9EC45F9-074A-48BF-92E9-A8CADD56F693}'
          # found using rededt32.exe at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{F9EC45F9-074A-48BF-92E9-A8CADD56F693}
          # DisplayName: UE4 Prerequisites (x64)
          # DisplayVersion: 1.0.11.0
        path: "{{ target }}/Engine/Extras/Redist/en-us/UE4PrereqSetup_x64.exe"
        arguments: /quiet

    ## TODO: DOES NOT ELIMINATE ERROR WITH XAudio2_7.dll
    ##- name: Unreal Editor {{ uever }} copy required old DLLs to UE4 bin, set 1
    ##  win_copy:
    ##    remote_src: yes
    ##    src: "{{ targetbintp }}/AppLocalDependencies/Win64/DirectX/"
    ##    dest: "{{ targetbin64 }}"

    ## TODO: ### UE4 Editor CRASHES WITH THIS:
    ##- name: "copy required old DLLs to UE4 bin, set 2"
    ##  win_copy:
    ##    remote_src: yes
    ##    src: "{{ targetbintp }}/CEF3/Win64/"
    ##    dest: "{{ targetbin64 }}"

    - name: Unreal Editor {{ uever }} shortcut
      win_shortcut:
        description: configured by Luar devops
        directory: "{{ targetbin64 }}"
        src: "{{ targetexe64 }}"
        icon: "{{ targetexe64 }},0"
        dest: "C:/Users/Public/Desktop/Unreal Editor {{ uever }}.lnk"
...
