---
## TODO: !!! BEGIN REQUIRED INTERNET ACCESS FOR Chocolatey
- include_tasks: atasks-win-firewall-off.yml

- name: Epic Games Launcher
  # https://chocolatey.org/packages/epicgameslauncher
  win_chocolatey:
    name: epicgameslauncher

- include_tasks: atasks-win-firewall-on.yml
## TODO: !!! END REQUIRED INTERNET ACCESS FOR Chocolatey
...
