---
- name: "firewall rule IN to block all UDP"
  win_firewall_rule:
    name: BLOCK IN ALL UDP
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: in
    protocol: UDP
    localport: any
...
