---
- name: "firewall rule IN for only Win RD and RM, lower TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BELOW WinRD 33
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: in
    protocol: TCP
    localport: 0-32

- name: "firewall rule IN for only Win RD and RM, middle TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BETWEEN WinRD 33 AND WinRM 5986
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: in
    protocol: TCP
    localport: 34-5985

- name: "firewall rule IN for only Win RD and RM, upper TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BEYOND WinRM 5986
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: in
    protocol: TCP
    localport: 5987-65535
...
