---
- name: "firewall rule IN for only WinRM, lower TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BELOW WinRM 5986
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: in
    protocol: TCP
    localport: 0-5985

- name: "firewall rule IN for only WinRM, upper TCP"
  win_firewall_rule:
    name: BLOCK IN ALL TCP BEYOND WinRM 5986
    group: __janelas__
    state: present
    enabled: "{{ janelas_firewall_rules_enabled }}"
    action: block
    direction: in
    protocol: TCP
    localport: 5987-65535
...
